# Generated by Django 3.0.7 on 2020-06-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_image', models.CharField(max_length=50)),
                ('is_user_logged', models.BooleanField()),
            ],
        ),
    ]
